# Generated by Django 4.0 on 2021-12-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='name',
            field=models.CharField(default='Bibek Poudel', max_length=30),
        ),
    ]
