# Generated by Django 4.0 on 2021-12-26 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('email', models.EmailField(max_length=30, verbose_name='Visitor Email')),
                ('message', models.TextField(verbose_name='Visitor Message')),
            ],
        ),
        migrations.DeleteModel(
            name='User_Data',
        ),
    ]
