# Generated by Django 4.0 on 2021-12-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_visitordata_delete_user_data'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VisitorData',
            new_name='VisitorMessage',
        ),
    ]
