# Generated by Django 3.2.10 on 2021-12-27 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_visitordata_visitormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='work',
            field=models.CharField(default='Programmer', max_length=30),
        ),
    ]
