# Generated by Django 4.0 on 2021-12-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_visitordata_visitormessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='work',
            field=models.CharField(default='Programmer', max_length=150),
        ),
    ]
